export const WPLACE_FREE: number[][] = [
  [0,0,0],[60,60,60],[120,120,120],[210,210,210],[255,255,255],
  [96,0,24],[237,28,36],[255,127,39],[246,170,9],[249,221,59],[255,250,188],
  [14,185,104],[19,230,123],[135,255,94],
  [12,129,110],[16,174,166],[19,225,190],[96,247,242],
  [40,80,158],[64,147,228],
  [107,80,246],[153,177,251],
  [120,12,153],[170,56,185],[224,159,249],
  [203,0,122],[236,31,128],[243,141,169],
  [104,70,52],[149,104,42],[248,178,119],
];
export const WPLACE_PAID: number[][] = [
  [170,170,170],
  [165,14,30],[250,128,114],
  [228,92,26],[156,132,49],[197,173,49],[232,212,95],
  [74,107,58],[90,148,74],[132,197,115],
  [15,121,159],[187,250,242],[125,199,255],
  [77,49,184],[74,66,132],[122,113,196],[181,174,241],
  [155,82,73],[209,128,120],[250,182,164],
  [219,164,99],[123,99,82],[156,132,107],[214,181,148],
  [209,128,81],[255,197,165],
  [109,100,63],[148,140,107],[205,197,158],
  [51,57,65],[109,117,141],[179,185,209],
];
export const WPLACE_NAMES: Record<string,string> = {
  "0,0,0":"Black","60,60,60":"Dark Gray","120,120,120":"Gray","210,210,210":"Light Gray","255,255,255":"White",
  "96,0,24":"Deep Red","237,28,36":"Red","255,127,39":"Orange","246,170,9":"Gold","249,221,59":"Yellow","255,250,188":"Light Yellow",
  "14,185,104":"Dark Green","19,230,123":"Green","135,255,94":"Light Green",
  "12,129,110":"Dark Teal","16,174,166":"Teal","19,225,190":"Light Teal","96,247,242":"Cyan",
  "40,80,158":"Dark Blue","64,147,228":"Blue",
  "107,80,246":"Indigo","153,177,251":"Light Indigo",
  "120,12,153":"Dark Purple","170,56,185":"Purple","224,159,249":"Light Purple",
  "203,0,122":"Dark Pink","236,31,128":"Pink","243,141,169":"Light Pink",
  "104,70,52":"Dark Brown","149,104,42":"Brown","248,178,119":"Beige",
  "170,170,170":"Medium Gray","165,14,30":"Dark Red","250,128,114":"Light Red",
  "228,92,26":"Dark Orange","156,132,49":"Dark Goldenrod","197,173,49":"Goldenrod","232,212,95":"Light Goldenrod",
  "74,107,58":"Dark Olive","90,148,74":"Olive","132,197,115":"Light Olive",
  "15,121,159":"Dark Cyan","187,250,242":"Light Cyan","125,199,255":"Light Blue",
  "77,49,184":"Dark Indigo","74,66,132":"Dark Slate Blue","122,113,196":"Slate Blue","181,174,241":"Light Slate Blue",
  "155,82,73":"Dark Peach","209,128,120":"Peach","250,182,164":"Light Peach",
  "219,164,99":"Light Brown","123,99,82":"Dark Tan","156,132,107":"Tan","214,181,148":"Light Tan",
  "209,128,81":"Dark Beige","255,197,165":"Light Beige",
  "109,100,63":"Dark Stone","148,140,107":"Stone","205,197,158":"Light Stone",
  "51,57,65":"Dark Slate","109,117,141":"Slate","179,185,209":"Light Slate"
};
export const DEFAULT_FREE_KEYS = WPLACE_FREE.map(([r,g,b]) => `${r},${g},${b}`);
export const DEFAULT_PAID_KEYS: string[] = [];

// Auto-generated by png_to_bitmask_js.py
// Each tile is a 25-bit mask (1 = black, 0 = transparent),
// bits packed LSB-first in row-major order: bit = y*5 + x for (x,y) in [0..4].
export const SYMBOL_W = 5;
export const SYMBOL_H = 5;
export const SYMBOL_TILES = new Uint32Array([0x04ABAA4, 0x0489224, 0x0E8922E, 0x0A8D6AA, 0x0E8FEAE, 0x1FABB75, 0x0EFFFEE, 0x0EEEEEE, 0x1FAFEBF, 0x1FD82BF, 0x1F212BF, 0x0EDDEEA, 0x0AFBBEA, 0x094EE52, 0x0EAFA88, 0x0477FEA, 0x0EDD76E, 0x1BDA95C, 0x0367CD8, 0x0E8D62E, 0x1BDEF7F, 0x146F46F, 0x1577DD5, 0x0E756B5, 0x04739C4, 0x0ADD5C4, 0x0AD936A, 0x067F308, 0x04FBBEE, 0x1BD837B, 0x11701D1, 0x1E601E6, 0x1260126, 0x0F7BF14, 0x1FEE34C, 0x15A82B5, 0x0DB01B6, 0x077BD9E, 0x074C65C, 0x15756AE, 0x1B23AB5, 0x08C1062, 0x1CF18E3, 0x0477DD5, 0x11729D1, 0x1999A79, 0x1759577, 0x04F837B, 0x0E247FF, 0x1123891, 0x1B8923B, 0x0476DC4, 0x1466CC5, 0x071D71C, 0x15F29F5, 0x1BAA94E, 0x11F9231, 0x14D0754, 0x1BAC6BB, 0x0427C84, 0x15FD48E, 0x19A28B3, 0x04FFDC4, 0x0E8814A]);

// Example: test a bit (x,y) in tile i
// const idx = y * TILE_W + x;
// const bit = (TILES[i] >>> idx) & 1;
